Repository NCATComp410/comp410_fall_2022, pull requests merged in 2022-09, with the labels that each got.

#5 added aggie proud
  pii_detect.py
  test_pii_detect.py
Labels: T1

#8 That's What Aggies Do Commit
  pii_detect.py
  test_pii_detect.py
Labels: PhantomTroupe

#12 Merge with base repo
  pii_detect.py
  test_pii_detect.py
Labels: Frost

#13 added slogan
  pii_detect.py
  test_pii_detect.py
Labels: T1

#15 Added an Aggie slogan
  pii_detect.py
  test_pii_detect.py
Labels: T1

#21 updated pull
  pii_detect.py
  test_pii_detect.py
Labels: T2

#28 cdwilkie slogan
  pii_detect.py
  test_pii_detect.py
Labels: T2

#31 Updated slogan list with entry #19
  pii_detect.py
  test_pii_detect.py
Labels: PhantomTroupe

#32 Changed name of def
  pii_detect.py
  test_pii_detect.py
Labels: PhantomTroupe

#27 update
  pii_detect.py
  test_pii_detect.py
Labels: SEI

#34 Merge "main" with "main"
  pii_detect.py
  test_pii_detect.py
Labels: Frost
